module CitizenHelper
  def state_list
    [
      ['AC', 'Acre'],
      ['AL', 'Alagoas'],
      ['AM', 'Amazonas'],
      ['AP', 'Amapá'],
      ['BA', 'Bahia'],
      ['CE', 'Ceará'],
      ['DF', 'Distrito Federal'],
      ['ES', 'Espírito Santo'],
      ['GO', 'Goiás'],
      ['MA', 'Maranhão'],
      ['MG', 'Minas Gerais'],
      ['MS', 'Mato Grosso do Sul'],
      ['MT', 'Mato Grosso'],
      ['PA', 'Pará'],
      ['PB', 'Paraíba'],
      ['PE', 'Pernambuco'],
      ['PI', 'Piauí'],
      ['PR', 'Paraná'],
      ['RJ', 'Rio de Janeiro'],
      ['RN', 'Rio Grande do Norte'],
      ['RO', 'Rondônia'],
      ['RR', 'Roraima'],
      ['RS', 'Rio Grande do Sul'],
      ['SC', 'Santa Catarina'],
      ['SE', 'Sergipe'],
      ['SP', 'São Paulo'],
      ['TO', 'Tocantins']
    ]
  end

  def country_codes_list
    [
      ["93", "Afeganistão\tÁsia"],
      ["27", "África do Sul\tÁfrica"],
      ["355", "Albânia\tEuropa"],
      ["49", "Alemanha\tEuropa"],
      ["376", "Andorra\tEuropa"],
      ["244", "Angola\tÁfrica"],
      ["1", "Anguilla\tAmérica Central"],
      ["1", "Antígua e Barbuda\tAmérica Central"],
      ["599", "Antilhas Holandesas\tAmérica Central"],
      ["966", "Arábia Saudita\tÁsia"],
      ["213", "Argélia\tÁfrica"],
      ["54", "Argentina\tAmérica do Sul"],
      ["374", "Armênia\tÁsia"],
      ["297", "Aruba\tAmérica Central"],
      ["247", "Ascensão\tÁfrica"],
      ["61", "Austrália\tOceania"],
      ["43", "Áustria\tEuropa"],
      ["994", "Azerbaijão\tÁsia"],
      ["1", "Bahamas\tAmérica Central"],
      ["880", "Bangladesh\tÁsia"],
      ["1", "Barbados\tAmérica Central"],
      ["973", "Bahrein\tÁsia"],
      ["32", "Bélgica\tEuropa"],
      ["501", "Belize\tAmérica Central"],
      ["229", "Benim\tÁfrica"],
      ["1", "Bermudas\tAmérica Central"],
      ["375", "Bielorrússia\tEuropa"],
      ["591", "Bolívia\tAmérica do Sul"],
      ["387", "Bósnia e Herzegovina\tEuropa"],
      ["267", "Botswana\tÁfrica"],
      ["55", "Brasil\tAmérica do Sul"],
      ["673", "Brunei\tÁsia"],
      ["359", "Bulgária\tEuropa"],
      ["226", "Burkina Faso\tÁfrica"],
      ["257", "Burundi\tÁfrica"],
      ["975", "Butão\tÁsia"],
      ["238", "Cabo Verde\tÁfrica"],
      ["237", "Camarões\tÁfrica"],
      ["855", "Camboja\tÁsia"],
      ["1", "Canadá\tAmérica do Norte"],
      ["7", "Cazaquistão\tÁsia"],
      ["237", "Chade\tÁfrica"],
      ["56", "Chile\tAmérica do Sul"],
      ["86", "República Popular da China\tÁsia"],
      ["357", "Chipre\tEuropa"],
      ["57", "Colômbia\tAmérica do Sul"],
      ["269", "Comores\tÁfrica"],
      ["242", "Congo-Brazzaville\tÁfrica"],
      ["243", "Congo-Kinshasa\tÁfrica"],
      ["850", "Coreia do Norte\tÁsia"],
      ["82", "Coreia do Sul\tÁsia"],
      ["225", "Costa do Marfim\tÁfrica"],
      ["506", "Costa Rica\tAmérica Central"],
      ["385", "Croácia\tEuropa"],
      ["53", "Cuba\tAmérica Central"],
      ["45", "Dinamarca\tEuropa"],
      ["253", "Djibuti\tÁfrica"],
      ["1", "Dominica\tAmérica Central"],
      ["20", "Egipto\tÁfrica/Ásia"],
      ["503", "El Salvador\tAmérica Central"],
      ["971", "Emirados Árabes Unidos\tÁsia"],
      ["593", "Equador\tAmérica do Sul"],
      ["291", "Eritreia\tÁfrica"],
      ["421", "Eslováquia\tEuropa"],
      ["386", "Eslovénia\tEuropa"],
      ["34", "Espanha\tEuropa"],
      ["1", "Estados Unidos\tAmérica do Norte"],
      ["372", "Estónia\tEuropa"],
      ["251", "Etiópia\tÁfrica"],
      ["679", "Fiji\tOceania"],
      ["63", "Filipinas\tÁsia"],
      ["358", "Finlândia\tEuropa"],
      ["33", "França\tEuropa"],
      ["241", "Gabão\tÁfrica"],
      ["220", "Gâmbia\tÁfrica"],
      ["233", "Gana\tÁfrica"],
      ["995", "Geórgia\tÁsia"],
      ["350", "Gibraltar\tEuropa"],
      ["1", "Granada\tAmérica Central"],
      ["30", "Grécia\tEuropa"],
      ["299", "Groenlândia\tAmérica do Norte"],
      ["590", "Guadalupe\tAmérica Central"],
      ["671", "Guam\tOceania"],
      ["502", "Guatemala\tAmérica Central"],
      ["592", "Guiana\tAmérica do Sul"],
      ["594", "Guiana Francesa\tAmérica do Sul"],
      ["224", "Guiné\tÁfrica"],
      ["245", "Guiné-Bissau\tÁfrica"],
      ["240", "Guiné Equatorial\tÁfrica"],
      ["509", "Haiti\tAmérica Central"],
      ["504", "Honduras\tAmérica Central"],
      ["852", "Hong Kong\tÁsia"],
      ["36", "Hungria\tEuropa"],
      ["967", "Iêmen\tÁsia"],
      ["1", "Ilhas Cayman\tAmérica Central"],
      ["672", "Ilha Christmas\tOceania"],
      ["672", "Ilhas Cocos\tOceania"],
      ["682", "Ilhas Cook\tOceania"],
      ["298", "Ilhas Féroe\tEuropa"],
      ["672", "Ilha Heard e Ilhas McDonald\tOceania"],
      ["960", "Maldivas\tÁsia"],
      ["500", "Ilhas Malvinas\tAmérica do Sul"],
      ["1", "Ilhas Marianas do Norte\tOceania"],
      ["692", "Ilhas Marshall\tOceania"],
      ["672", "Ilha Norfolk\tOceania"],
      ["677", "Ilhas Salomão\tOceania"],
      ["1", "Ilhas Virgens Americanas\tAmérica Central"],
      ["1", "Ilhas Virgens Britânicas\tAmérica Central"],
      ["91", "Índia\tÁsia"],
      ["62", "Indonésia\tÁsia/Oceania"],
      ["98", "Irã\tÁsia"],
      ["964", "Iraque\tÁsia"],
      ["353", "Irlanda\tEuropa"],
      ["354", "Islândia\tEuropa"],
      ["972", " Israel\tÁsia"],
      ["39", "Itália\tEuropa"],
      ["1", "Jamaica\tAmérica Central"],
      ["81", "Japão\tÁsia"],
      ["962", "Jordânia\tÁsia"],
      ["686", "Kiribati\tOceania"],
      ["383", "Kosovo\tEuropa"],
      ["965", "Kuwait\tÁsia"],
      ["856", "Laos\tÁsia"],
      ["266", "Lesoto\tÁfrica"],
      ["371", "Letônia\tEuropa"],
      ["961", "Líbano\tÁsia"],
      ["231", "Libéria\tÁfrica"],
      ["218", "Líbia\tÁfrica"],
      ["423", "Liechtenstein\tEuropa"],
      ["370", "Lituânia\tEuropa"],
      ["352", "Luxemburgo\tEuropa"],
      ["853", "Macau\tÁsia"],
      ["389", "República da Macedônia\tEuropa"],
      ["261", "Madagascar\tÁfrica"],
      ["60", "Malásia\tÁsia"],
      ["265", "Malawi\tÁfrica"],
      ["223", "Mali\tÁfrica"],
      ["356", "Malta\tEuropa"],
      ["212", "Marrocos\tÁfrica"],
      ["596", "Martinica\tAmérica Central"],
      ["230", "Maurícia\tÁfrica"],
      ["222", "Mauritânia\tÁfrica"],
      ["269", "Mayotte\tÁfrica"],
      ["52", "México\tAmérica do Norte"],
      ["691", "Estados Federados da Micronésia\tOceania"],
      ["258", "Moçambique\tÁfrica"],
      ["373", "Moldávia\tEuropa"],
      ["377", "Mônaco\tEuropa"],
      ["976", "Mongólia\tÁsia"],
      ["382", "Montenegro\tEuropa"],
      ["1", "Montserrat\tAmérica Central"],
      ["95", "Myanmar\tÁsia"],
      ["264", "Namíbia\tÁfrica"],
      ["674", "Nauru\tOceania"],
      ["977", "Nepal\tÁsia"],
      ["505", "Nicarágua\tAmérica Central"],
      ["227", "Níger\tÁfrica"],
      ["234", "Nigéria\tÁfrica"],
      ["683", "Niue\tOceania"],
      ["47", "Noruega\tEuropa"],
      ["687", "Nova Caledônia\tOceania"],
      ["64", "Nova Zelândia\tOceania"],
      ["968", "Omã\tÁsia"],
      ["31", "Países Baixos\tEuropa"],
      ["680", "Palau\tOceania"],
      ["970", "Palestina\tÁsia"],
      ["507", "Panamá\tAmérica Central"],
      ["675", "Papua-Nova Guiné\tOceania"],
      ["92", "Paquistão\tÁsia"],
      ["595", "Paraguai\tAmérica do Sul"],
      ["51", "Peru\tAmérica do Sul"],
      ["689", "Polinésia Francesa\tOceania"],
      ["48", "Polônia\tEuropa"],
      ["1", "Porto Rico\tAmérica Central"],
      ["351", "Portugal\tEuropa"],
      ["974", "Qatar\tÁsia"],
      ["254", "Quênia\tÁfrica"],
      ["996", "Quirguistão\tÁsia"],
      ["44", "Reino Unido\tEuropa"],
      ["236", "República Centro-Africana\tÁfrica"],
      ["1", "República Dominicana\tAmérica Central"],
      ["420", "República Tcheca\tEuropa"],
      ["262", "Reunião\tÁfrica"],
      ["40", "Romênia\tEuropa"],
      ["250", "Ruanda\tÁfrica"],
      ["7", "Rússia\tEuropa/Ásia"],
      ["212", "Saara Ocidental\tÁfrica"],
      ["685", "Samoa\tOceania"],
      ["1", "Samoa Americana\tOceania"],
      ["290", "Santa Helena (território)\tÁfrica"],
      ["1", "Santa Lúcia\tAmérica Central"],
      ["1", "São Cristóvão e Nevis\tAmérica Central"],
      ["378", "São Marinho\tEuropa"],
      ["508", "Saint-Pierre e Miquelon\tAmérica do Norte"],
      ["239", "São Tomé e Príncipe\tÁfrica"],
      ["1", "São Vicente e Granadinas\tAmérica Central"],
      ["248", "Seicheles\tÁfrica"],
      ["221", "Senegal\tÁfrica"],
      ["232", "Serra Leoa\tÁfrica"],
      ["381", "Sérvia\tEuropa"],
      ["65", "Singapura\tÁsia"],
      ["963", "Síria\tÁsia"],
      ["252", "Somália\tÁfrica"],
      ["94", "Sri Lanka\tÁsia"],
      ["268", "Suazilândia\tÁfrica"],
      ["249", "Sudão\tÁfrica"],
      ["211", "Sudão do Sul\tÁfrica"],
      ["46", "Suécia\tEuropa"],
      ["41", "Suíça\tEuropa"],
      ["597", "Suriname\tAmérica do Sul"],
      ["992", "Tadjiquistão\tÁsia"],
      ["66", "Tailândia\tÁsia"],
      ["886", "República da China\tÁsia"],
      ["255", "Tanzânia\tÁfrica"],
      ["246", "Território Britânico do Oceano Índico\tÁfrica"],
      ["670", "Timor-Leste\tÁsia"],
      ["228", "Togo\tÁfrica"],
      ["690", "Tokelau\tOceania"],
      ["676", "Tonga\tOceania"],
      ["1", "Trinidad e Tobago\tAmérica Central"],
      ["216", "Tunísia\tÁfrica"],
      ["1", "Turcas e Caicos\tAmérica Central"],
      ["993", "Turquemenistão\tÁsia"],
      ["90", "Turquia\tÁsia//Europa"],
      ["688", "Tuvalu\tOceania"],
      ["380", "Ucrânia\tEuropa"],
      ["256", "Uganda\tÁfrica"],
      ["598", "Uruguai\tAmérica do Sul"],
      ["998", "Uzbequistão\tÁsia"],
      ["678", "Vanuatu\tOceania"],
      ["379", "Vaticano\tEuropa"],
      ["58", "Venezuela\tAmérica do Sul"],
      ["84", "Vietnã\tÁsia"],
      ["681", "Wallis e Futuna\tOceania"],
      ["260", "Zâmbia\tÁfrica"],
      ["263", "Zimbábue\tÁfrica"]
    ]
  end
end
