module CitizenHelper
  def state_list
    [
      ['AC', 'Acre'],
      ['AL', 'Alagoas'],
      ['AM', 'Amazonas'],
      ['AP', 'Amapá'],
      ['BA', 'Bahia'],
      ['CE', 'Ceará'],
      ['DF', 'Distrito Federal'],
      ['ES', 'Espírito Santo'],
      ['GO', 'Goiás'],
      ['MA', 'Maranhão'],
      ['MG', 'Minas Gerais'],
      ['MS', 'Mato Grosso do Sul'],
      ['MT', 'Mato Grosso'],
      ['PA', 'Pará'],
      ['PB', 'Paraíba'],
      ['PE', 'Pernambuco'],
      ['PI', 'Piauí'],
      ['PR', 'Paraná'],
      ['RJ', 'Rio de Janeiro'],
      ['RN', 'Rio Grande do Norte'],
      ['RO', 'Rondônia'],
      ['RR', 'Roraima'],
      ['RS', 'Rio Grande do Sul'],
      ['SC', 'Santa Catarina'],
      ['SE', 'Sergipe'],
      ['SP', 'São Paulo'],
      ['TO', 'Tocantins']
    ]
  end

  def country_codes_list
    [
      ["93", "AF", "Afeganistão"],
      ["27", "ZA", "África do Sul"],
      ["355", "AL", "Albânia"],
      ["49", "DE", "Alemanha"],
      ["376", "AD", "Andorra"],
      ["244", "AO", "Angola"],
      ["1", "AI", "Anguilla"],
      ["1", "AQ", "Antárctida"],
      ["599", "AG", "Antígua e Barbuda"],
      ["966", "SA", "Arábia Saudita"],
      ["213", "DZ", "Argélia"],
      ["54", "AR", "Argentina"],
      ["374", "AM", "Arménia"],
      ["297", "AW", "Aruba"],
      ["247", "AU", "Austrália"],
      ["61", "AT", "Áustria"],
      ["43", "AZ", "Azerbaijão"],
      ["994", "BS", "Bahamas"],
      ["1", "BD", "Bangladesh"],
      ["880", "BB", "Barbados"],
      ["1", "BH", "Barein"],
      ["973", "BE", "Bélgica"],
      ["32", "BZ", "Belize"],
      ["501", "BJ", "Benim"],
      ["229", "BM", "Bermuda"],
      ["1", "BY", "Bielorússia"],
      ["375", "BO", "Bolívia, Estado Plurinacional da"],
      ["591", "BQ", "Bonaire, Santo Eustáquio e Saba"],
      ["387", "BA", "Bósnia-Herzegóvina"],
      ["267", "BW", "Botsuana"],
      ["55", "BR", "Brasil"],
      ["673", "BN", "Brunei"],
      ["359", "BG", "Bulgária"],
      ["226", "BF", "Burkina Faso"],
      ["257", "BI", "Burundi"],
      ["975", "BT", "Butão"],
      ["238", "CV", "Cabo Verde"],
      ["237", "CM", "Camarões"],
      ["855", "KH", "Cambodja"],
      ["1", "CA", "Canadá"],
      ["7", "KZ", "Cazaquistão"],
      ["237", "TD", "Chade"],
      ["56", "CL", "Chile"],
      ["86", "CN", "China"],
      ["357", "CY", "Chipre"],
      ["57", "CO", "Colômbia"],
      ["269", "KM", "Comoros"],
      ["242", "CG", "Congo"],
      ["243", "CD", "Congo, República Democrática do"],
      ["850", "KP", "Coreia, República Popular Democrática de"],
      ["82", "KR", "Coreia, República da"],
      ["225", "CR", "Costa Rica"],
      ["506", "CI", "Costa do Marfim"],
      ["385", "HR", "Croácia"],
      ["53", "CU", "Cuba"],
      ["45", "CW", "Curação"],
      ["253", "DK", "Dinamarca"],
      ["1", "DJ", "Djibouti"],
      ["20", "DM", "Dominica"],
      ["503", "EG", "Egipto"],
      ["971", "SV", "El Salvador"],
      ["593", "AE", "Emirados Árabes Unidos"],
      ["291", "EC", "Equador"],
      ["421", "ER", "Eritreia"],
      ["386", "SK", "Eslováquia"],
      ["34", "SI", "Eslovénia"],
      ["1", "ES", "Espanha"],
      ["372", "US", "Estados Unidos"],
      ["251", "EE", "Estónia"],
      ["679", "ET", "Etiópia"],
      ["63", "RU", "Federação Russa"],
      ["358", "FJ", "Fiji"],
      ["33", "PH", "Filipinas"],
      ["241", "FI", "Finlândia"],
      ["220", "FR", "França"],
      ["233", "GA", "Gabão"],
      ["995", "GM", "Gâmbia"],
      ["350", "GH", "Gana"],
      ["1", "GE", "Geórgia"],
      ["30", "GS", "Geórgia do Sul e Ilhas Sandwich do Sul"],
      ["299", "GI", "Gibraltar"],
      ["590", "GD", "Granada"],
      ["671", "GR", "Grécia"],
      ["502", "GL", "Gronelândia"],
      ["592", "GP", "Guadalupe"],
      ["594", "GU", "Guam"],
      ["224", "GT", "Guatemala"],
      ["245", "GG", "Guernsey"],
      ["240", "GY", "Guiana"],
      ["509", "GF", "Guiana Francesa"],
      ["504", "GN", "Guiné"],
      ["852", "GQ", "Guiné Equatorial"],
      ["36", "GW", "Guiné-Bissáu"],
      ["967", "HT", "Haiti"],
      ["1", "HN", "Honduras"],
      ["672", "HK", "Hong Kong"],
      ["672", "HU", "Hungria"],
      ["682", "BV", "Ilha Bouvet"],
      ["298", "HM", "Ilha Heard e Ilhas McDonald"],
      ["672", "CX", "Ilha Natal"],
      ["960", "NF", "Ilha Norfolk"],
      ["500", "RE", "Ilha Reunião"],
      ["1", "IM", "Ilha de Man"],
      ["692", "AX", "Ilhas Åland"],
      ["672", "KY", "Ilhas Caimão"],
      ["677", "CC", "Ilhas Cocos"],
      ["1", "CK", "Ilhas Cook"],
      ["1", "FK", "Ilhas Falkland (Malvinas)"],
      ["91", "FO", "Ilhas Feroé"],
      ["62", "MP", "Ilhas Marianas do Norte"],
      ["98", "MH", "Ilhas Marshall"],
      ["964", "UM", "Ilhas Menores Exteriores dos Estados Unidos"],
      ["353", "SB", "Ilhas Salomão"],
      ["354", "TC", "Ilhas Turks e Caicos"],
      ["972", "VG", "Ilhas Virgens, Britânicas"],
      ["39", "VI", "Ilhas Virgens, Estados Unidos"],
      ["1", "IN", "Índia"],
      ["81", "ID", "Indonésia"],
      ["962", "IR", "Irão, República Islâmica do"],
      ["686", "IQ", "Iraque"],
      ["383", "IE", "Irlanda"],
      ["965", "IS", "Islândia"],
      ["856", "IL", "Israel"],
      ["266", "IT", "Itália"],
      ["371", "JM", "Jamaica"],
      ["961", "JP", "Japão"],
      ["231", "JE", "Jersey"],
      ["218", "JO", "Jordânia"],
      ["423", "KI", "Kiribati"],
      ["370", "KW", "Kuwait"],
      ["352", "LS", "Lesoto"],
      ["853", "LV", "Letónia"],
      ["389", "LB", "Líbano"],
      ["261", "LR", "Libéria"],
      ["60", "LY", "Líbia"],
      ["265", "LI", "Liechtenstein"],
      ["223", "LT", "Lituânia"],
      ["356", "LU", "Luxemburgo"],
      ["212", "MO", "Macau"],
      ["596", "MK", "Macedónia, República"],
      ["230", "MG", "Madagáscar"],
      ["222", "MY", "Malásia"],
      ["269", "MW", "Malawi"],
      ["52", "MV", "Maldivas"],
      ["691", "ML", "Mali"],
      ["258", "MT", "Malta"],
      ["373", "MA", "Marrocos"],
      ["377", "MQ", "Martinica"],
      ["976", "MU", "Maurícias"],
      ["382", "MR", "Mauritânia"],
      ["1", "YT", "Mayotte"],
      ["95", "MX", "México"],
      ["264", "FM", "Micronesia, Estados Federados da"],
      ["674", "MZ", "Moçambique"],
      ["977", "MD", "Moldávia, República da"],
      ["505", "MC", "Mónaco"],
      ["227", "MN", "Mongólia"],
      ["234", "ME", "Montenegro"],
      ["683", "MS", "Montserrat"],
      ["47", "MM", "Myanmar"],
      ["687", "NA", "Namíbia"],
      ["64", "NR", "Nauru"],
      ["968", "NP", "Nepal"],
      ["31", "NI", "Nicarágua"],
      ["680", "NE", "Níger"],
      ["970", "NG", "Nigéria"],
      ["507", "NU", "Niue"],
      ["675", "NO", "Noruega"],
      ["92", "NC", "Nova Caledónia"],
      ["595", "NZ", "Nova Zelândia"],
      ["51", "OM", "Oman"],
      ["689", "NL", "Países Baixos"],
      ["48", "PW", "Palau"],
      ["1", "PS", "Palestina, Autoridade da"],
      ["351", "PA", "Panamá"],
      ["974", "PG", "Papua Nova Guiné"],
      ["254", "PK", "Paquistão"],
      ["996", "PY", "Paraguai"],
      ["44", "PE", "Peru"],
      ["236", "PN", "Pitcairn"],
      ["1", "PF", "Polinésia Francesa"],
      ["420", "PL", "Polónia"],
      ["262", "PR", "Porto Rico"],
      ["40", "PT", "Portugal"],
      ["250", "QA", "Quatar"],
      ["7", "KE", "Quénia"],
      ["212", "KG", "Quirgistão"],
      ["685", "GB", "Reino Unido"],
      ["1", "SY", "República Árabe Síria"],
      ["290", "CF", "República Centro-Africana"],
      ["1", "CZ", "República Checa"],
      ["1", "LA", "República Democrática Popular do Laos"],
      ["378", "DO", "República Dominicana"],
      ["508", "SS", "República do Sudão"],
      ["239", "RO", "Roménia"],
      ["1", "RW", "Ruanda"],
      ["248", "EH", "Sahara Ocidental"],
      ["221", "BL", "Saint Barthélemy"],
      ["232", "KN", "Saint Kitts e Nevis"],
      ["381", "PM", "Saint Pierre e Miquelon"],
      ["65", "WS", "Samoa"],
      ["963", "AS", "Samoa Americana"],
      ["252", "SM", "San Marino"],
      ["94", "SH", "Santa Helema, Ascenção e Tristão da Cunha"],
      ["268", "LC", "Santa Lúcia"],
      ["249", "VA", "Santa Sé (Estado Cidade do Vaticano)"],
      ["211", "MF", "São Martin (Território Francês)"],
      ["46", "SX", "São Martinho (Países Baixos)"],
      ["41", "ST", "São Tomé e Príncipe"],
      ["597", "VC", "São Vicente e Grenadinas"],
      ["992", "SN", "Senegal"],
      ["66", "SL", "Serra Leoa"],
      ["886", "RS", "Sérvia"],
      ["255", "SC", "Seychelles"],
      ["246", "SG", "Singapura"],
      ["670", "SO", "Somália"],
      ["228", "LK", "Sri Lanka"],
      ["690", "SZ", "Suazilândia"],
      ["676", "SD", "Sudão"],
      ["1", "SE", "Suécia"],
      ["216", "CH", "Suíça"],
      ["1", "SR", "Suriname"],
      ["993", "SJ", "Svalbard e Jan Mayen"],
      ["90", "TJ", "Tadjaquistão"],
      ["688", "TH", "Tailândia"],
      ["380", "TW", "Taiwan"],
      ["256", "TZ", "Tanzânia, República Unida da"],
      ["598", "IO", "Território Britânico do Oceano Índico"],
      ["998", "TF", "Territórios Franceses do Sul"],
      ["678", "TL", "Timor-Leste"],
      ["379", "TG", "Togo"],
      ["58", "TK", "Tokelau"],
      ["84", "TO", "Tonga"],
      ["681", "TT", "Trinidade e Tobago"],
      ["260", "TN", "Tunísia"],
      ["263", "TM", "Turcomenistão"]
    ]
  end
end
